
volumes:
  pg_data:

services:
  postgres:
    container_name: db
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tododb
  app:
    container_name: app
    build: .
    depends_on:
      - postgres
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tododb
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "80:8080"
