
spring:
  main:
    banner-mode: off
  jpa:
    show-sql: false

  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    name: mainDS
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true

  management:
    health:
      livenessState:
        enabled: true
      readinessState:
        enabled: true
    endpoint:
      health:
        probes:
          enabled: true
      prometheus:
        enabled: true
    endpoints:
      web:
        exposure:
          include: prometheus